sudo: false
language: c
os: linux
install:
  - git clone https://github.com/nim-lang/nim
  - cd nim
  - ./bootstrap.sh
  - export PATH=$(pwd)/bin:$PATH
  - nim e install_nimble.nims
  - nimble install
  - cd ..
before_script:
  - set -e
  - export PATH=$(pwd)/nim/bin:$(pwd):$PATH
script:
  - nim c c2nim.nim
  - nim c -r testsuite/tester.nim
